routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['guest']],function(){

    Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login','Auth\LoginController@login');
    Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/reset','Auth\ResetPasswordController@reset');
    Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('password.reset');

});

Route::group(['middleware' => ['auth']],function(){

    Route::post('logout','Auth\LoginController@logout')->name('logout');

    /* Dashboard */
    Route::get('/dashboard', 'PagesController@dashboard');


    /* Clients */
    Route::get('/clients/create', 'ClientsController@create');
    Route::post('clients/create', 'ClientsController@store');
    Route::get('/clients/all', 'ClientsController@index')->name('clients.index');
    Route::get('/clients/{id}/edit', 'ClientsController@edit');
    Route::put('clients/{id}/edit', 'ClientsController@update')->name('clients.update');
    Route::delete('clients/{id}','ClientsController@destroy')->name('clients.destroy');

    /* Quotes */

    Route::get('/quotes/create', 'QuotesController@create');
    Route::post('quotes/create', 'QuotesController@store');
    Route::get('/quotes/all', 'QuotesController@index')->name('quotes.index');
    Route::get('/quotes/{id}/edit', 'QuotesController@edit');
    Route::put('/quotes/{id}/edit', 'QuotesController@update')->name('quotes.update');
    Route::delete('/quotes/{id}','QuotesController@destroy')->name('quotes.destroy');
    Route::get('/quotes/word','QuotesWordController@index')->name('quotes.word');
    Route::get('/quotes/{id}/word','QuotesWordController@show')->name('quotes.show');
    /* Sales */
    Route::resource('sales','SalesController');

    /* Users */
    Route::resource('users','UsersController');
});

app/Sale.php
<?php

namespace App;

use App\Events\SaleCreated;
use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $fillable = ['quote_id', 'client_id', 'user_id', 'status', 'equipment_cost', 'delivery_address', 'sale_type', 'payment_options', 'email_record', 'sale_date', 'completion_delivery_date', 'collection_delivery', 'trip_mileage',
    	'cost_per_mile', 'delivery_cost', 'ral_colour', 'graphics', 'sim_card_received', 'training_required', 'training_date', 'training_location', 'training_cost','mailed'];
    protected $guarded = ['id'];
    protected $casts = [
        'sale_type' => 'json'
    ];
    protected $events = [
        'saved' => SaleCreated::class,

    ];

    public function graphicsFilePath()
    {
        return public_path('saleImages') .'/' . $this->graphics;
    }

    public function graphicsAssetPath()
    {
        if (empty($this->graphics))
        {
            return null;
        }
        return asset('saleImages') .'/' . $this->graphics;
    }
    public function setGraphicsAttribute($file)
    {
        if (!is_null($this->graphics) && file_exists($this->graphicsFilePath()))
        {
            unlink($this->graphicsFilePath());
        }

        $extension = $file->getClientOriginalExtension();

        $oldFileName = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

        $fileName = $oldFileName .'-'. str_random(10).'.'.$extension;

        $file->move(public_path('saleImages'),$fileName);

        $this->attributes['graphics'] = $fileName;

    }


}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Http\Requests\SalesStore;
use App\Quote;
use App\Sale;
use App\User;
use Illuminate\Http\Request;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('sales.index',['sales' => Sale::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $clients = Client::all();
        $users = User::all();
        $quoteId = null;
        $quoteClient = null;
        $quoteSale = null;
        $quoteClientAdd = null;
        
        if ($request->get('quote_id'))
        {
            $quote = Quote::find($request->get('quote_id'));
            $quoteId = $quote->id;
            $quoteClient = $quote->client_id;
            $quoteSale = $quote->user_id;
            $quoteClientAdd = Client::find($quote->client_id)->delivery_address;
        }

        return view('sales.create',compact('clients','users','quoteId','quoteClient','quoteSale','quoteClientAdd'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SalesStore $request)
    {
        $data = $request->all();
        try{
            Sale::create($data);
        }
        catch(\Swift_TransportException $e)
        {
            return redirect()->route('sales.index')->withErrors('sale email didn\'t sent but the sale has been created');
        }

        return redirect()->route('sales.index')->with('status','The sale has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sale = Sale::findOrFail($id);
        $clients = Client::all();
        $users = User::all();

        return view('sales.edit',compact('sale','clients','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SalesStore $request, $id)
    {
        $sale = Sale::findOrFail($id);

        $sale->update($request->all());

        return redirect()->route('sales.index')->with('status','The sale has been updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Sale::where('id',$id)->delete();

        return redirect()->route('sales.index')->with('status','sale deleted successfully');

    }
}

resources/views/sales/index.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="inner-wrapper">
        <!-- start: sidebar -->
        <aside id="sidebar-left" class="sidebar-left">

            <div class="sidebar-header">
                <div class="sidebar-title">
                    Navigation
                </div>
                <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
                    <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                </div>
            </div>

            <div class="nano">
                <div class="nano-content">
                    <nav id="menu" class="nav-main" role="navigation">

                        <ul class="nav nav-main">
                            <li>
                                <a href="/dashboard">
                                    <i class="fa fa-home" aria-hidden="true"></i>
                                    <span>Dashboard</span>
                                </a>
                            </li>
                            <li class="nav-parent">
                                <a href="#">
                                    <i class="fa fa-address-card-o" aria-hidden="true"></i>
                                    <span>Clients</span>
                                </a>
                                <ul class="nav nav-children">
                                    <li>
                                        <a href="/clients/create">
                                            Enter New Client
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/clients/all">
                                            View All Clients
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-parent ">
                                <a href="#">
                                    <i class="fa fa-bar-chart" aria-hidden="true"></i>
                                    <span>Quotes</span>
                                </a>
                                <ul class="nav nav-children">
                                    <li>
                                        <a href="/quotes/create">
                                            Enter New Quote
                                        </a>
                                    </li>
                                    <li >
                                        <a href="/quotes/all">
                                            View All Quotes
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-parent nav-expanded nav-active">
                                <a href="#">
                                    <i class="fa fa-cart-plus" aria-hidden="true"></i>
                                    <span>Sales</span>
                                </a>
                                <ul class="nav nav-children">
                                    <li>
                                        <a href="/sales/create">
                                            Enter New Sale
                                        </a>
                                    </li>
                                    <li class="nav-active">
                                        <a href="/sales">
                                            View All Sales
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-parent">
                                <a href="#">
                                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                                    <span>Users</span>
                                </a>
                                <ul class="nav nav-children">
                                    <li>
                                        <a href="/users/create">
                                            Enter New User
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/users">
                                            View All Users
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <script>
                                // Maintain Scroll Position
                                if (typeof localStorage !== 'undefined') {
                                    if (localStorage.getItem('sidebar-left-position') !== null) {
                                        var initialPosition = localStorage.getItem('sidebar-left-position'),
                                                sidebarLeft = document.querySelector('#sidebar-left .nano-content');

                                        sidebarLeft.scrollTop = initialPosition;
                                    }
                                }
                            </script>
                    </nav>
                </div>
            </div>
        </aside>
        <!-- end: sidebar -->

        <section role="main" class="content-body">
            <header class="page-header">
                <h2>View All Sales</h2>

                <div class="right-wrapper pull-right">
                    <ol class="breadcrumbs">
                        <li>
                            <a href="/dashboard">
                                <i class="fa fa-home"></i>
                            </a>
                        <li><span>Sales</span></li>
                        <li><span>View All Sales</span></li>
                        </li>
                    </ol>

                    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
                </div>
            </header>

            <!-- start: page -->
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-sales">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Quote ID</th>
                        <th>Client ID</th>
                        <th>Sales Representative</th>
                        <th>Status</th>
                        <th>Equipment Cost</th>
                        <th>Delivery Address</th>
                        <th>Sale Type </th>
                        <th>Payment Options</th>
                        <th>Email Record</th>
                        <th>Sale Date</th>
                        <th>Completion &amp; Delivery Date</th>
                        <th>Collection / Delivery</th>
                        <th>Trip Mileage</th>
                        <th>Cost Per Mile</th>
                        <th>Deivery Cost</th>
                        <th>Ral Colour</th>
                        <th>Sim Card Received</th>
                        <th>Training Required</th>
                        <th>Date Booked</th>
                        <th>Training Required</th>
                        <th>Training Cost</th>

                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($sales as $sale)
                        <tr>

                            <td>{!! $sale->id !!}</td>
                            <td>{!! $sale->quote_id !!}</td>
                            <td>{!! $sale->client_id !!}</td>
                            <td>{!! $sale->user_id !!}</td>
                            <td style="color: @if($sale->status =='delivered') green; @else red; @endif">{!! $sale->status !!}</td>
                            <td>{!! $sale->equipment_cost !!}</td>
                            <td>{!! $sale->delivery_address !!}</td>
                            <td>{!! implode(',',$sale->sale_type) !!}</td>
                            <td>{!! $sale->payment_options !!}</td>
                            <td>{!! $sale->email_record !!}</td>
                            <td>{!! $sale->sale_date !!}</td>
                            <td>{!! $sale->completion_delivery_date !!}</td>
                            <td>{!! $sale->collection_delivery !!}</td>
                            <td>{!! $sale->trip_mileage !!}</td>
                            <td>{!! $sale->cost_per_mile !!}</td>
                            <td>{!! $sale->delivery_cost !!}</td>
                            <td>{!! $sale->ral_colour !!}</td>
                            <td>{!! $sale->sim_card_received !!}</td>
                            <td>{!! $sale->training_required !!}</td>
                            <td>{!! $sale->training_date !!}</td>
                            <td>{!! $sale->training_location !!}</td>
                            <td>{!! $sale->training_cost !!}</td>

                            <td>
                                <a href="{!! route('sales.edit',$sale->id) !!}" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Update</a>

                                <form method="POST" id="delete-{{$sale->id}}"  action="{{route('sales.destroy',$sale->id)}}">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}

                                </form>
                                <a href="#" onclick="$('#delete-'+{{$sale->id}}).submit()" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove-sign"></i> Delete</a>
                            </td>
                        </tr>

                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- end: page -->



            @endsection

            @section('footer')
                <script>
                    $(document).ready(function(){
                        $('#datatable-sales').DataTable();
                    });
                </script>
@endsection

resources/views/sales/scripts.blade.php
<script>

    $(document).ready(function(){
        $('#client_id').on('change',function(){
            $('#delivery_address').val($('option:selected', this).attr('address'));
        });

        $('#sale_date').on('change',function(){
            var sale_date = $(this).val().split('/');

            var date = new Date(sale_date[0] + '-' + sale_date[1] + '-' + sale_date[2]);
            date.setDate(date.getDate() + 28);
            year = date.getFullYear();
            month = date.getMonth()+1;
            dt = date.getDate();

            if (dt < 10) {
                dt = '0' + dt;
            }
            if (month < 10) {
                month = '0' + month;
            }
            $('#completion_delivery_date').val(year+'/' + month + '/'+dt);

        });


        $('#collection_delivery').on('change',function(){

            var value = $(this).val().toLowerCase();

            if (value == 'delivery')
            {
                $('.delivery').attr('readonly',false);
            }
            else
            {
                $('.delivery').attr('readonly',true);
            }
        });

        $('#trip_mileage').on('change',function(){
            $('#delivery_cost').val($('#cost_per_mile').val() * $(this).val());
        });

        $('#cost_per_mile').on('change',function(){
            $('#delivery_cost').val($('#trip_mileage').val() * $(this).val());
        });

        $('#training_required').on('change',function(){
            var value = $(this).val().toLowerCase();

            if (value == 'yes')
            {
                $('.training').attr('disabled',false);
            }
            else
            {
                $('.training').attr('disabled',true);
            }
        });
    });
</script>